### ISSUE TITLE
[API] drawRect() not aligned to pixel grid

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#10]
When using the built-in drawRect(), I get this:
![image](https://user-images.githubusercontent.com/4740954/68417235-403eeb00-0153-11ea-88ce-178a60c5d658.png)

I would expect it to look like this:
![image](https://user-images.githubusercontent.com/4740954/68417290-606eaa00-0153-11ea-8e1f-d5e30fbd7ce5.png)

This is most likely due to pixel boundary alignment on line segment endpoints. This might be another case for replacing the built-in draw calls.

Here is the code implementing pixel-perfect rectangles in Groovy:
```Groovy
    void drawPixelRect(int x, int y, int width, int height, int color) {
        for (def i in x..x+width) {
            drawPixel(color, i, y)
            drawPixel(color, i, y+height)
        }
        for (def i in y..y+height) {
            drawPixel(color, x, i)
            drawPixel(color, x+width, i)
        }
    }
```

**Comment by Torbuntu** [comment]
The built in will definitely need replacing like the drawLineSegment calls. Thanks for the snippet! It will definitely help.

**Comment by Torbuntu** [comment]
Fixed, will be in next release!
