### ISSUE TITLE
[Bug] Sprites not showing (program.properties)

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#19]
Leikr is unable to display sprites without a `program.properties` file (even a blank one). Adding even a blank `program.properties` file allows sprite display to work.

See attached project setup for an example.
[LeikrShooter.zip](https://github.com/Torbuntu/Leikr/files/3887289/LeikrShooter.zip)

**Comment by Torbuntu** [comment]
Fixed for version 0.0.16
