### ISSUE TITLE
[Bug] Mouse "cursor" visible at all times

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#20]
**Describe the bug**
I get a 2px wide "cursor" placed approximately at my mouse's position. I say "approximately" because it seems to be offset a couple pixels in the positive `x` and `y` directions.

**To Reproduce**
1. Open Leikr
2. Use the following code:
```Groovy
class CursorDemo extends leikr.Engine {
    void render() {
        bgColor(1)
    }
}
```
3. Move mouse over Leikr window
4. Observe black "cursor" following the mouse around

**Expected behavior**
Mouse position would not be visible unless explicitly tying something to `mouseX()` and `mouseY()`.

**Screenshots**
![leikr-cursor-pixels2](https://user-images.githubusercontent.com/4740954/69580462-d8313700-0f91-11ea-97a2-58b0c42cdeff.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - N/A
 - 0.0.15

**Comment by Torbuntu** [comment]
Fixed for version 0.0.16
