### ISSUE TITLE
Allow leikr programs to use arguments from the command line

### ISSUE THREAD

**Issue by Uberoverlord** [Torbuntu/Leikr#21]
**Is your feature request related to a problem? Please describe.**
Some programs would benefit from the user being able to send information from the in-leikr terminal. (IE, the user could change certain constants in a simulation from the terminal)

**Describe the solution you'd like**
`create` ought to take a string array parameter consisting of every (whitespace delimited) command line argument. This is the way it is done on a lot of systems and in a lot of languages (C and Java come to mind) so it will be a very familiar solution to most programmers. This way if I `run example hello` then leikr programs will be empowered to know the user sent `hello` as the first command line argument

**Comment by Torbuntu** [comment]
I added the option to use either `create()` , `create(String[] args)` or both if you'd like. In Master now, will be in release 0.0.16
