### ISSUE TITLE
Make `getPixel()` return RGB

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#22]
**Is your feature request related to a problem? Please describe.**
`getPixel()` returns an indexed color. While that's nice, it doesn't let me do more advanced sampling-based pixel manipulation.

**Describe the solution you'd like**
`getPixel()` should return an RGB string, or an object with discrete R, G, and B values.

**Describe alternatives you've considered**
`getPixel()` could also return the *closest* color to the sampled value, but restricting `getPixel()` where other methods are not restricted is inconsistent.

**Comment by Torbuntu** [comment]
Modified the `getPixel(x,y)` command to now just return the RGB String "255,255,255" format. Will be in release 0.0.16.
