### ISSUE TITLE
Unable to load anything other than PNGs with `drawTexture()`

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#27]
**Describe the bug**
When I specify the file extension for a texture, Leikr automatically appends `.png` to the filename. If I use a jpeg or add `.png` to the texture filename myself, it is still appended with `.png`.

**To Reproduce**
1. Load any asset from the Art folder as a texture, specifying file extension
2. File is not loaded unless it's a) a PNG, and b) the extension is not added in code

**Expected behavior**
If I enter a file extension, Leikr should load that regardless of type (provided it's a supported image type). If extensionless behavior is desired, Leikr should default to PNG and appending the extension *only* when the extension is not specified.

**Screenshots**
![image](https://user-images.githubusercontent.com/4740954/71273814-35aa7080-2311-11ea-8604-a77f62118ef5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.0.16

**Additional context**

**Comment by Torbuntu** [comment]
Fixed in 0.0.17
bmp and jpg are now supported, extensions types are now required as part of the names.
