### ISSUE TITLE
`ProgramName` not immediately available after `new ProgramName`

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#28]
**Describe the bug**
When initializing a new program with `new ProgramName`, then ProgramName is not available in the run list without running `ls`.

**To Reproduce**
1. Initialize with `new ProgramName`
2. Use up/down to select programs, observe that ProgramName is not in the list.
3. Run `ls`
4. Program now appears

**Expected behavior**
Leikr should know about my program as soon as it creates the folder, since it is doing so internally. I understand the triviality of this request.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Torbuntu** [comment]
Quick note, this functionality will be completely changed in 0.0.17, so I'll check back in after that to see if it still doesn't work.

**Comment by Torbuntu** [comment]
Though I could have sworn I fixed this in 0.0.16...

**Comment by Torbuntu** [comment]
Is this one still an issue from master since the terminal history was changed?

**Comment by pixelbath** [comment]
Looks like it's resolved.
