### ISSUE TITLE
Screen resizing hotkey

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#29]
**Is your feature request related to a problem? Please describe.**
Though Leikr can scale to arbitrary sizes, I would like to switch between (or snap to) a different resolution that draws pixels at a fixed ratio, like 1:1, 2:1, the original 3:1, and so on.

**Describe the solution you'd like**
I would like a hotkey to switch between fixed pixel ratios. Perhaps something like `Ctrl+1`, `Ctrl+2` for 1:1 and 2:1 aspect ratios, respectively. It is assumed that Leikr running on Raspberry Pi would be already fixed at 1:1.

**Describe alternatives you've considered**
I considered using extra buttons on gamepads to open a sort-of hypervisor screen to manage screen settings and other things for Leikr, but the specs are fixed on controllers already, and users using actual SNES-like pads will have no system-supported option. Besides, any console-like environment will likely already have its scaling ratio pre-set.

**Additional context**

**Comment by Torbuntu** [comment]
Master has been updated with `Ctrl+1`, `Ctrl+2`, `Ctrl+3` on both the Terminal screen and the Engine Pause screen for scaling the window. 1 starts at the default (which is 240*3, 160*3) and then goes up from there.

A quick note. The "hardware" version will be running on a raspberry pi, and it will be in full screen with no other desktop software running. So, when that happens I don't know how the resizing is going to behave. Will maybe need to disable it on the Pi around that time. But that isn't a worry right now.

The hypervisor type idea sounds cool. Maybe a sort of "settings" screen could be added (under Pause screen?)

**Comment by pixelbath** [comment]
This is what I was referring to with 1:1 pixel ratio. 1 pixel in the Leikr framebuffer = 1 pixel on the physical screen.
![image](https://user-images.githubusercontent.com/4740954/71546048-ad028480-294f-11ea-9af3-a2d335418517.png)

This was achived by multiplying the screen size by the number pressed, like so:
```
    if (Mdx.input.isKeyJustPressed(Keys.NUM_1)) {
        Gdx.graphics.setWindowedMode(240 * 1, 160 * 1);
    }
    if (Mdx.input.isKeyJustPressed(Keys.NUM_2)) {
        Gdx.graphics.setWindowedMode(240 * 2, 160 * 2);
    }
    if (Mdx.input.isKeyJustPressed(Keys.NUM_3)) {
        Gdx.graphics.setWindowedMode(240 * 3, 160 * 3);
    }
```
I'm fine with the default being 3:1, but I do like having the option of smaller screenshots / smaller gif captures.

**Comment by Torbuntu** [comment]
Oh! That makes sense. We can change that down to make it 1:1 etc... 

Updated master

**Comment by Torbuntu** [comment]
Now that the changes are 1:1, 2:1 etc... is this issue acceptably complete?
