### ISSUE TITLE
Using an out-of-bounds sprite index gives generic error

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#32]
**Describe the bug**
When selecting a sprite index that does not exist (possibly because I used the wrong sprite size), Leikr gives the very general error: `Error in program 'render' method. null`

**To Reproduce**
1. Call `sprite()` with an invalid index id (try `sprite(32, 0, 0, 1)`)
2. See message.

**Expected behavior**
A clearer error message, something like "Sprite index out of bounds"

**Screenshots**
![image](https://user-images.githubusercontent.com/4740954/71526797-b4fdee00-2895-11ea-8154-48ee33b577e7.png)

**Comment by Torbuntu** [comment]
![image](https://user-images.githubusercontent.com/17347324/71545778-9c084200-2954-11ea-9aec-55bb9d9c114d.png)
How does this look?

**Comment by Torbuntu** [comment]
Added for 0.0.17
