### ISSUE TITLE
Calling `drawMap()` without `loadMap()` yields unspecific error

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#35]
**Describe the bug**
When calling `drawMap()` without first having called `loadMap`, Leikr gives the error `Error in program 'render' method: null`.

**To Reproduce**
1. Put a `drawMap()` call into the `render()` method of a new program
2. Run it
3. See error

**Expected behavior**
An error like `drawMap: No map loaded.` or something to indicate the call causing the error and the reason why.

**Comment by Torbuntu** [comment]
Fixed in 0.0.17
