### ISSUE TITLE
Gif export does not match actual framerate

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#37]
**Describe the bug**
When exporting a gif, the gif's framerate does not actually match the display framerate. This may be a desirable effect in certain scenarios, however.

**To Reproduce**
1. Make something that drops the framerate in Leikr
2. Capture a gif while displaying the framerate
3. Playback exported gif, see framerate is butter-smooth

**Expected behavior**
I'm not sure if this is actually a bug, but maybe a toggle to capture actual vs. "smooth" framerate

**Screenshots**
![Uploading recording1579222900.gif…]()

- Version - Latest

**Comment by Torbuntu** [comment]
I think bumping the default gif recording from 30fps to 60 (which is Leikr's default fps it tries to run) might fix this. I pushed this change to Master if you want to try.

**Comment by Torbuntu** [comment]
Most likely due to the plugin being used for gif recording. Closing for now.
