### ISSUE TITLE
Remove/change Mini2Dx logo from startup

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#4]
While I'm sure they appreciate the free press, the wiki and readme have this information spelled out. I think it breaks the "console" immersion a bit if the startup of the system shows a graphic that's not the same resolution.

Solution: Either drop the Mini2Dx logo, or alter it to be in-line with Leikr's graphics specifications (more pixelated and conforming to the palette).

**Comment by Torbuntu** [comment]
[Fixed in this commit](https://github.com/Torbuntu/Leikr/commit/18697f66a99a613a7b29a0a30b8b261c0ed8f455)

I just removed it all together. Like you mentioned, it is very well documented all over. Removing to promote the aesthetic.
