### ISSUE TITLE
Program icons

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#5]
If possible, the finished .jar file should use the Leikr logo. Likewise, the executing program should have a matching icon.

![image](https://user-images.githubusercontent.com/4740954/68331650-96982500-0092-11ea-8eb4-9d322f0cb558.png)

**Comment by Torbuntu** [comment]
[Fix Version](https://github.com/Torbuntu/Leikr/commit/18697f66a99a613a7b29a0a30b8b261c0ed8f455)

Added a window icon to replace the lwjgl icon. 

I cannot find a way to change the jar icon. This will potentially require making cross platform launch icons (.desktop entry for Linux and .exe for windows).
