### ISSUE TITLE
Leikr not reading program folder dynamically

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#6]
If I say `load ProgramName` in Leikr, and that program was created while Leikr is running, that program is not usable until I restart Leikr and I get the error message "Program [ProgramName] does not exist in Programs directory"

Conversely, I do not need to `load` a program to have it updated after editing; I can simply exit the program and call `run` over and over to see changes. The program does not seem to be held in memory separate from disk.

**Comment by Torbuntu** [comment]
Running LS in the terminal will refresh the Program Directory listing. So a restart is not required. Once a program is loaded, it just loads the pointer to execute. Actually running the program loads the most current of everything.

**Comment by pixelbath** [comment]
What happens when I'm shown "Loaded program `ProgramName`" ? Does that mean it freshly reloaded the program, or does that happen again on run?

**Comment by Torbuntu** [comment]
That means it set the pointer to that program, so when you type "run" with no extra params itll run that program. So in reality, load is kind of stupid and pointless in this sense because one could just always use run [program]

**Comment by Torbuntu** [comment]
Removed the useless "load" command and run now properly checks for if a program exists or not.
