### ISSUE TITLE
[Core] Screen scale factor

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#7]
It would be nice to specify the scaling factor of the Leikr screen. The default currently seems to be 2 (double size pixels), but I'd like to specify no scaling or even higher if possible.

Seems like `system.properties` would be a good place for this.

![image](https://user-images.githubusercontent.com/4740954/68333036-0dceb880-0095-11ea-8d9e-bcf2f226a606.png)

**Comment by Torbuntu** [comment]
How do you mean scaling? The window is resizeable and uses a viewport that should maintain the aspect ratio of 240x160 (the Leikr resolution).

**Comment by pixelbath** [comment]
I assumed everything was drawn 1:1 into a buffer, then *that* was resized to the final output. The viewport works and keeps the correct aspect ratio, but the pixels themselves aren't scaled.

As an example, here is DrawTests rendered at 2560x1440:
![image](https://user-images.githubusercontent.com/4740954/68343471-1a114080-00aa-11ea-9c1c-40c94772c103.png)

I'd expect these lines to be pretty chunky, but it looks like they're just normal lines with exaggerated thickness.

**Comment by Torbuntu** [comment]
Fixed in version 0.0.14
