### ISSUE TITLE
[API] drawPixel inconsistent

### ISSUE THREAD

**Issue by pixelbath** [Torbuntu/Leikr#8]
The `drawPixel` function takes an index as a color argument, but many of the other methods take a color via `setColor` which allows for RGB strings of arbitrary values, and some (`drawString`) take either indexed or RGB string and *do not* use the `setColor` method.

Solution: Either add more overrides to other drawing methods, or use `setColor()` for all color input.

**Comment by Torbuntu** [comment]
I will add overrides with ID on the other drawing method. That just clearly makes sense.

**Comment by Torbuntu** [comment]
Added overrides to the rest of the colors and ordered them properly.
